# Generated by Django 5.2.14 on 2026-05-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_seed_per_grade_group_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionpricingplan',
            name='badge_text',
        ),
        migrations.RemoveField(
            model_name='admissionpricingplan',
            name='badge_text_en',
        ),
        migrations.RemoveField(
            model_name='admissionpricingplan',
            name='badge_text_kk',
        ),
        migrations.RemoveField(
            model_name='admissionpricingplan',
            name='badge_text_ru',
        ),
    ]
