# Generated by Django 5.2.14 on 2026-05-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_drop_pricingplan_badge_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionvariant',
            name='og_image',
        ),
    ]
