# Generated by Django 5.2.14 on 2026-05-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0005_seed_inactive_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Сегмент в URL: open-day-2026. Уникален в пределах региона.', max_length=200, verbose_name='Slug')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок (h1)')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Заголовок (h1)')),
                ('title_kk', models.CharField(max_length=300, null=True, verbose_name='Заголовок (h1)')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Заголовок (h1)')),
                ('lead', models.TextField(blank=True, help_text='Опционально: 1–2 предложения для превью и meta description.', verbose_name='Лид')),
                ('lead_ru', models.TextField(blank=True, help_text='Опционально: 1–2 предложения для превью и meta description.', null=True, verbose_name='Лид')),
                ('lead_kk', models.TextField(blank=True, help_text='Опционально: 1–2 предложения для превью и meta description.', null=True, verbose_name='Лид')),
                ('lead_en', models.TextField(blank=True, help_text='Опционально: 1–2 предложения для превью и meta description.', null=True, verbose_name='Лид')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='Обложка')),
                ('cover_caption', models.CharField(blank=True, max_length=300, verbose_name='Подпись под обложкой')),
                ('cover_caption_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подпись под обложкой')),
                ('cover_caption_kk', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подпись под обложкой')),
                ('cover_caption_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подпись под обложкой')),
                ('cover_alt', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется title.', max_length=300, verbose_name='Alt-текст обложки')),
                ('cover_alt_ru', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется title.', max_length=300, null=True, verbose_name='Alt-текст обложки')),
                ('cover_alt_kk', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется title.', max_length=300, null=True, verbose_name='Alt-текст обложки')),
                ('cover_alt_en', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется title.', max_length=300, null=True, verbose_name='Alt-текст обложки')),
                ('content', models.TextField(help_text='HTML рендерится через |safe. Используй h2/h3/h4, p, ul/ol/li, blockquote+cite, a, img, figure+figcaption, small.', verbose_name='Содержимое (HTML)')),
                ('content_ru', models.TextField(help_text='HTML рендерится через |safe. Используй h2/h3/h4, p, ul/ol/li, blockquote+cite, a, img, figure+figcaption, small.', null=True, verbose_name='Содержимое (HTML)')),
                ('content_kk', models.TextField(help_text='HTML рендерится через |safe. Используй h2/h3/h4, p, ul/ol/li, blockquote+cite, a, img, figure+figcaption, small.', null=True, verbose_name='Содержимое (HTML)')),
                ('content_en', models.TextField(help_text='HTML рендерится через |safe. Используй h2/h3/h4, p, ul/ol/li, blockquote+cite, a, img, figure+figcaption, small.', null=True, verbose_name='Содержимое (HTML)')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(db_index=True, help_text='Сортировка ленты и показ даты на карточке.', verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-published_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('region', 'slug'), name='event_region_slug_unique')],
            },
        ),
    ]
