# Generated by Django 5.2.14 on 2026-05-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_seed_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(help_text='Обязательное поле в админке. Сид-миграции/legacy-записи могут быть без файла — в шаблоне сработает fallback на плейсхолдер «Нет фото».', null=True, upload_to='events/covers/', verbose_name='Обложка'),
        ),
    ]
