# Generated by Django 5.2.14 on 2026-05-19 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='og_description',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_description → lead.', max_length=300, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='event',
            name='og_description_en',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_description → lead.', max_length=300, null=True, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='event',
            name='og_description_kk',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_description → lead.', max_length=300, null=True, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='event',
            name='og_description_ru',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_description → lead.', max_length=300, null=True, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='event',
            name='og_image',
            field=models.ImageField(blank=True, help_text='1200×630 для соцсетей. Если пусто — fallback на обложку события.', null=True, upload_to='events/og/', verbose_name='OG/share картинка'),
        ),
        migrations.AddField(
            model_name='event',
            name='og_title',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_title → title.', max_length=80, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='event',
            name='og_title_en',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_title → title.', max_length=80, null=True, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='event',
            name='og_title_kk',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_title → title.', max_length=80, null=True, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='event',
            name='og_title_ru',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_title → title.', max_length=80, null=True, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_description',
            field=models.CharField(blank=True, help_text='150–160 символов. Если пусто — fallback на lead.', max_length=200, verbose_name='SEO description (meta)'),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_description_en',
            field=models.CharField(blank=True, help_text='150–160 символов. Если пусто — fallback на lead.', max_length=200, null=True, verbose_name='SEO description (meta)'),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_description_kk',
            field=models.CharField(blank=True, help_text='150–160 символов. Если пусто — fallback на lead.', max_length=200, null=True, verbose_name='SEO description (meta)'),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_description_ru',
            field=models.CharField(blank=True, help_text='150–160 символов. Если пусто — fallback на lead.', max_length=200, null=True, verbose_name='SEO description (meta)'),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_title',
            field=models.CharField(blank=True, help_text='50–60 символов. Если пусто — fallback на title.', max_length=80, verbose_name='SEO title (<title>)'),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='50–60 символов. Если пусто — fallback на title.', max_length=80, null=True, verbose_name='SEO title (<title>)'),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_title_kk',
            field=models.CharField(blank=True, help_text='50–60 символов. Если пусто — fallback на title.', max_length=80, null=True, verbose_name='SEO title (<title>)'),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_title_ru',
            field=models.CharField(blank=True, help_text='50–60 символов. Если пусто — fallback на title.', max_length=80, null=True, verbose_name='SEO title (<title>)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Опционально. Если не загружена — на сайте покажется плейсхолдер «Нет фото».', null=True, upload_to='events/covers/', verbose_name='Обложка'),
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Ссылка в шорткоде: [[gallery slug=ЭТО]]. Уникален в пределах события.', max_length=64, verbose_name='Slug')),
                ('title', models.CharField(blank=True, help_text='Внутренняя метка для админки; не выводится на сайте.', max_length=200, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='events.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Фотогалерея',
                'verbose_name_plural': 'Фотогалереи',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/galleries/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, help_text='Опциональный figcaption под картинкой.', max_length=300, verbose_name='Подпись')),
                ('caption_ru', models.CharField(blank=True, help_text='Опциональный figcaption под картинкой.', max_length=300, null=True, verbose_name='Подпись')),
                ('caption_kk', models.CharField(blank=True, help_text='Опциональный figcaption под картинкой.', max_length=300, null=True, verbose_name='Подпись')),
                ('caption_en', models.CharField(blank=True, help_text='Опциональный figcaption под картинкой.', max_length=300, null=True, verbose_name='Подпись')),
                ('alt', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется подпись или название галереи.', max_length=300, verbose_name='Alt-текст')),
                ('alt_ru', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется подпись или название галереи.', max_length=300, null=True, verbose_name='Alt-текст')),
                ('alt_kk', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется подпись или название галереи.', max_length=300, null=True, verbose_name='Alt-текст')),
                ('alt_en', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется подпись или название галереи.', max_length=300, null=True, verbose_name='Alt-текст')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.eventgallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Фото в галерее',
                'verbose_name_plural': 'Фото в галерее',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventgallery',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='event_gallery_event_slug_unique'),
        ),
    ]
