# Generated by Django 5.2.14 on 2026-05-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_og_description_event_og_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='og_image',
        ),
    ]
