# Generated by Django 5.2.14 on 2026-05-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0005_seed_inactive_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Машинное имя: sports / creative / academic.', max_length=40, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=80, null=True, verbose_name='Название')),
                ('title_kk', models.CharField(max_length=80, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=80, null=True, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Секция активностей',
                'verbose_name_plural': 'Секции активностей',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('class_range', models.CharField(blank=True, help_text='Подзаголовок в шапке аккордеона (напр. «1–5 класс»).', max_length=60, verbose_name='Классы (подзаголовок)')),
                ('class_range_ru', models.CharField(blank=True, help_text='Подзаголовок в шапке аккордеона (напр. «1–5 класс»).', max_length=60, null=True, verbose_name='Классы (подзаголовок)')),
                ('class_range_kk', models.CharField(blank=True, help_text='Подзаголовок в шапке аккордеона (напр. «1–5 класс»).', max_length=60, null=True, verbose_name='Классы (подзаголовок)')),
                ('class_range_en', models.CharField(blank=True, help_text='Подзаголовок в шапке аккордеона (напр. «1–5 класс»).', max_length=60, null=True, verbose_name='Классы (подзаголовок)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('location', models.CharField(blank=True, help_text='Где проходят занятия (общее для всех групп кружка).', max_length=120, verbose_name='Локация')),
                ('location_ru', models.CharField(blank=True, help_text='Где проходят занятия (общее для всех групп кружка).', max_length=120, null=True, verbose_name='Локация')),
                ('location_kk', models.CharField(blank=True, help_text='Где проходят занятия (общее для всех групп кружка).', max_length=120, null=True, verbose_name='Локация')),
                ('location_en', models.CharField(blank=True, help_text='Где проходят занятия (общее для всех групп кружка).', max_length=120, null=True, verbose_name='Локация')),
                ('notes', models.TextField(blank=True, help_text='TODO / пробелы в данных. Не показывается публично.', verbose_name='Заметки (внутренние)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='regions.region', verbose_name='Регион')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='activities.activitysection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Кружок',
                'verbose_name_plural': 'Кружки',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Напр. «Младшие», «1–4 классы». Может быть пустым, если группа одна.', max_length=120, verbose_name='Название группы')),
                ('label_ru', models.CharField(blank=True, help_text='Напр. «Младшие», «1–4 классы». Может быть пустым, если группа одна.', max_length=120, null=True, verbose_name='Название группы')),
                ('label_kk', models.CharField(blank=True, help_text='Напр. «Младшие», «1–4 классы». Может быть пустым, если группа одна.', max_length=120, null=True, verbose_name='Название группы')),
                ('label_en', models.CharField(blank=True, help_text='Напр. «Младшие», «1–4 классы». Может быть пустым, если группа одна.', max_length=120, null=True, verbose_name='Название группы')),
                ('classes_min', models.PositiveSmallIntegerField(blank=True, help_text='Для фильтра по классам. Пусто — без ограничений.', null=True, verbose_name='Минимальный класс')),
                ('classes_max', models.PositiveSmallIntegerField(blank=True, help_text='Для фильтра по классам. Пусто — без ограничений.', null=True, verbose_name='Максимальный класс')),
                ('price', models.PositiveIntegerField(blank=True, help_text='Целое число тенге за месяц. Пусто — цена не указана.', null=True, verbose_name='Стоимость, ₸/мес')),
                ('students_status', models.CharField(choices=[('recruiting', 'Идёт набор'), ('has_places', 'Есть свободные места'), ('full', 'Заполнено')], default='recruiting', max_length=20, verbose_name='Статус набора')),
                ('min_students', models.PositiveSmallIntegerField(default=5, verbose_name='Минимум учеников')),
                ('max_students', models.PositiveSmallIntegerField(default=20, verbose_name='Максимум учеников')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='activities.activity', verbose_name='Кружок')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Окончание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='activities.activitygroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Слот расписания',
                'verbose_name_plural': 'Слоты расписания',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Имя')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, help_text='Нормализованный формат +77051234567 для tel:-ссылок.', max_length=20, verbose_name='Телефон (E.164)')),
                ('phone_display', models.CharField(blank=True, help_text='Удобочитаемый: 8 (705) 123-45-67.', max_length=40, verbose_name='Телефон (для показа)')),
                ('bio', models.TextField(blank=True, verbose_name='Био')),
                ('bio_ru', models.TextField(blank=True, null=True, verbose_name='Био')),
                ('bio_kk', models.TextField(blank=True, null=True, verbose_name='Био')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Био')),
                ('photo', models.ImageField(blank=True, upload_to='activities/teachers/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Опционально: если данные неполные, можно оставить пустым.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='activities.teacher', verbose_name='Преподаватель'),
        ),
    ]
