# Generated by Django 5.2.14 on 2026-05-12 12:59
#
# Помимо auto-AlterField, добавлена RunPython: заполняем `classes = [1..11]`
# у групп, где он остался пустым (обозначение «все классы»). После этой
# миграции в БД не должно быть групп с classes=[].

import activities.models
import django.contrib.postgres.fields
from django.db import migrations, models


def fill_empty_classes(apps, schema_editor):
    Group = apps.get_model('activities', 'ActivityGroup')
    for g in Group.objects.filter(classes=[]):
        g.classes = list(range(1, 12))
        g.save(update_fields=['classes'])


def clear_filled_classes(apps, schema_editor):
    """Обратимая часть: если откатываемся, групп с classes==[1..11] вернём в []."""
    Group = apps.get_model('activities', 'ActivityGroup')
    full = list(range(1, 12))
    for g in Group.objects.filter(classes=full):
        g.classes = []
        g.save(update_fields=['classes'])


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_classes_array_drop_class_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitygroup',
            name='classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=activities.models.default_all_classes, help_text='Список классов, в которых занимаются — напр. [3, 4, 5, 6]. По умолчанию — все классы 1–11. Min/max и текст в шапке аккордеона считаются автоматически.', size=11, verbose_name='Классы'),
        ),
        migrations.RunPython(fill_empty_classes, clear_filled_classes),
        migrations.AlterField(
            model_name='activitygroup',
            name='label',
            field=models.CharField(blank=True, help_text='Опциональное название (напр. «Младшие», «Продвинутые»). Если пусто — подставляется авто-диапазон из `classes`.', max_length=120, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='activitygroup',
            name='label_en',
            field=models.CharField(blank=True, help_text='Опциональное название (напр. «Младшие», «Продвинутые»). Если пусто — подставляется авто-диапазон из `classes`.', max_length=120, null=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='activitygroup',
            name='label_kk',
            field=models.CharField(blank=True, help_text='Опциональное название (напр. «Младшие», «Продвинутые»). Если пусто — подставляется авто-диапазон из `classes`.', max_length=120, null=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='activitygroup',
            name='label_ru',
            field=models.CharField(blank=True, help_text='Опциональное название (напр. «Младшие», «Продвинутые»). Если пусто — подставляется авто-диапазон из `classes`.', max_length=120, null=True, verbose_name='Название группы'),
        ),
    ]
