# Generated by Django 5.2.14 on 2026-05-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activitygroup_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='notes',
        ),
    ]
