# Generated by Django 5.2.14 on 2026-05-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_activity_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Показывать в секции «Внеклассные» на странице программы.', verbose_name='Избранный'),
        ),
    ]
