# Generated by Django 5.2.14 on 2026-05-18 13:32
# Manually reordered: AddField → RunPython (migrate data) → RemoveField → DeleteModel.
# Тренер был отдельной моделью с N:M обратной связью через Activity.teacher FK.
# 2026-05-18 решили упростить: имя/телефон/био хранятся прямо на Activity как строки.

from django.db import migrations, models


def migrate_teacher_data(apps, schema_editor):
    """Скопировать teacher.name/phone/bio в новые поля Activity.teacher_*.

    Работает между AddField (teacher_*) и RemoveField (teacher FK) / DeleteModel.
    """
    Activity = apps.get_model('activities', 'Activity')
    qs = Activity.objects.exclude(teacher__isnull=True).select_related('teacher')
    for activity in qs:
        t = activity.teacher
        activity.teacher_name = t.name or ''
        activity.teacher_name_ru = getattr(t, 'name_ru', '') or ''
        activity.teacher_name_kk = getattr(t, 'name_kk', '') or ''
        activity.teacher_name_en = getattr(t, 'name_en', '') or ''
        activity.teacher_phone = t.phone or ''
        activity.teacher_bio = t.bio or ''
        activity.teacher_bio_ru = getattr(t, 'bio_ru', '') or ''
        activity.teacher_bio_kk = getattr(t, 'bio_kk', '') or ''
        activity.teacher_bio_en = getattr(t, 'bio_en', '') or ''
        activity.save(update_fields=[
            'teacher_name', 'teacher_name_ru', 'teacher_name_kk', 'teacher_name_en',
            'teacher_phone',
            'teacher_bio', 'teacher_bio_ru', 'teacher_bio_kk', 'teacher_bio_en',
        ])


def noop(apps, schema_editor):
    """Reverse — no-op. Восстановление Teacher справочника требует обратной
    миграции (создаётся отдельно, если когда-нибудь понадобится)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_clean_label_weekly'),
    ]

    operations = [
        # === 1. AddField: новые поля на Activity (teacher_* + переводы) ===
        migrations.AddField(
            model_name='activity',
            name='teacher_name',
            field=models.CharField(blank=True, help_text='Имя ведущего тренера. Опционально.', max_length=120, verbose_name='Тренер — имя'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher_name_ru',
            field=models.CharField(blank=True, help_text='Имя ведущего тренера. Опционально.', max_length=120, null=True, verbose_name='Тренер — имя'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher_name_kk',
            field=models.CharField(blank=True, help_text='Имя ведущего тренера. Опционально.', max_length=120, null=True, verbose_name='Тренер — имя'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher_name_en',
            field=models.CharField(blank=True, help_text='Имя ведущего тренера. Опционально.', max_length=120, null=True, verbose_name='Тренер — имя'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher_phone',
            field=models.CharField(blank=True, help_text='Нормализованный +77051234567. В UI публичной страницы пока не показывается.', max_length=20, verbose_name='Тренер — телефон (E.164)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher_bio',
            field=models.TextField(blank=True, help_text='1–2 предложения про тренера. Опционально.', verbose_name='Тренер — био'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher_bio_ru',
            field=models.TextField(blank=True, help_text='1–2 предложения про тренера. Опционально.', null=True, verbose_name='Тренер — био'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher_bio_kk',
            field=models.TextField(blank=True, help_text='1–2 предложения про тренера. Опционально.', null=True, verbose_name='Тренер — био'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher_bio_en',
            field=models.TextField(blank=True, help_text='1–2 предложения про тренера. Опционально.', null=True, verbose_name='Тренер — био'),
        ),

        # === 2. Data: copy Teacher.* → Activity.teacher_* ===
        migrations.RunPython(migrate_teacher_data, reverse_code=noop),

        # === 3. RemoveField/DeleteModel ===
        migrations.RemoveField(
            model_name='activity',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),

        # === 4. Alter Activity.name max_length 200 → 60 ===
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name_kk',
            field=models.CharField(max_length=60, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Название'),
        ),
    ]
