# Generated by Django 5.2.14 on 2026-05-18 13:51
# Manually edited: AddField на ActivityGroup → RunPython (наследование с Activity) →
# RemoveField с Activity. Тренер переехал с уровня кружка на уровень группы
# (разные группы одного кружка могут вести разные тренера).

from django.db import migrations, models


def inherit_teacher_from_activity(apps, schema_editor):
    """Скопировать activity.teacher_* в каждую активную группу этого кружка.

    Один кружок может иметь N групп — после миграции все они получат одного
    и того же тренера. Менеджер потом сможет разделить.
    """
    ActivityGroup = apps.get_model('activities', 'ActivityGroup')
    for group in ActivityGroup.objects.select_related('activity'):
        a = group.activity
        group.teacher_name = getattr(a, 'teacher_name', '') or ''
        group.teacher_name_ru = getattr(a, 'teacher_name_ru', '') or ''
        group.teacher_name_kk = getattr(a, 'teacher_name_kk', '') or ''
        group.teacher_name_en = getattr(a, 'teacher_name_en', '') or ''
        group.teacher_phone = getattr(a, 'teacher_phone', '') or ''
        group.teacher_bio = getattr(a, 'teacher_bio', '') or ''
        group.teacher_bio_ru = getattr(a, 'teacher_bio_ru', '') or ''
        group.teacher_bio_kk = getattr(a, 'teacher_bio_kk', '') or ''
        group.teacher_bio_en = getattr(a, 'teacher_bio_en', '') or ''
        group.save(update_fields=[
            'teacher_name', 'teacher_name_ru', 'teacher_name_kk', 'teacher_name_en',
            'teacher_phone',
            'teacher_bio', 'teacher_bio_ru', 'teacher_bio_kk', 'teacher_bio_en',
        ])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_remove_activity_teacher_activity_teacher_bio_and_more'),
    ]

    operations = [
        # === 1. AddField teacher_* на ActivityGroup ===
        migrations.AddField(
            model_name='activitygroup',
            name='teacher_name',
            field=models.CharField(blank=True, help_text='Имя ведущего тренера этой группы. У разных групп одного кружка могут быть разные тренера.', max_length=120, verbose_name='Тренер — имя'),
        ),
        migrations.AddField(
            model_name='activitygroup',
            name='teacher_name_ru',
            field=models.CharField(blank=True, help_text='Имя ведущего тренера этой группы. У разных групп одного кружка могут быть разные тренера.', max_length=120, null=True, verbose_name='Тренер — имя'),
        ),
        migrations.AddField(
            model_name='activitygroup',
            name='teacher_name_kk',
            field=models.CharField(blank=True, help_text='Имя ведущего тренера этой группы. У разных групп одного кружка могут быть разные тренера.', max_length=120, null=True, verbose_name='Тренер — имя'),
        ),
        migrations.AddField(
            model_name='activitygroup',
            name='teacher_name_en',
            field=models.CharField(blank=True, help_text='Имя ведущего тренера этой группы. У разных групп одного кружка могут быть разные тренера.', max_length=120, null=True, verbose_name='Тренер — имя'),
        ),
        migrations.AddField(
            model_name='activitygroup',
            name='teacher_phone',
            field=models.CharField(blank=True, help_text='Нормализованный +77051234567. В UI публичной страницы пока не показывается.', max_length=20, verbose_name='Тренер — телефон (E.164)'),
        ),
        migrations.AddField(
            model_name='activitygroup',
            name='teacher_bio',
            field=models.TextField(blank=True, help_text='1–2 предложения про тренера. Опционально.', verbose_name='Тренер — био'),
        ),
        migrations.AddField(
            model_name='activitygroup',
            name='teacher_bio_ru',
            field=models.TextField(blank=True, help_text='1–2 предложения про тренера. Опционально.', null=True, verbose_name='Тренер — био'),
        ),
        migrations.AddField(
            model_name='activitygroup',
            name='teacher_bio_kk',
            field=models.TextField(blank=True, help_text='1–2 предложения про тренера. Опционально.', null=True, verbose_name='Тренер — био'),
        ),
        migrations.AddField(
            model_name='activitygroup',
            name='teacher_bio_en',
            field=models.TextField(blank=True, help_text='1–2 предложения про тренера. Опционально.', null=True, verbose_name='Тренер — био'),
        ),

        # === 2. Data: inherit с activity на каждую группу ===
        migrations.RunPython(inherit_teacher_from_activity, reverse_code=noop),

        # === 3. RemoveField teacher_* с Activity ===
        migrations.RemoveField(model_name='activity', name='teacher_bio'),
        migrations.RemoveField(model_name='activity', name='teacher_bio_en'),
        migrations.RemoveField(model_name='activity', name='teacher_bio_kk'),
        migrations.RemoveField(model_name='activity', name='teacher_bio_ru'),
        migrations.RemoveField(model_name='activity', name='teacher_name'),
        migrations.RemoveField(model_name='activity', name='teacher_name_en'),
        migrations.RemoveField(model_name='activity', name='teacher_name_kk'),
        migrations.RemoveField(model_name='activity', name='teacher_name_ru'),
        migrations.RemoveField(model_name='activity', name='teacher_phone'),
    ]
