# Generated by Django 5.2.14 on 2026-05-19 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_swap_robotics_for_school_life'),
        ('regions', '0005_seed_inactive_cities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'Фото в галерее', 'verbose_name_plural': 'Фото в галерее'},
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Устаревшее. Категория теперь привязана к Album.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='gallery.gallerycategory', verbose_name='Категория (legacy)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_wide',
            field=models.BooleanField(default=False, help_text='Растягивает карточку на 2 колонки в мозаике. Авто-определяется по aspect ratio при upload (>=1.4 → wide), можно переключить вручную.', verbose_name='Широкая карточка'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Устаревшее. Сортировка теперь по дате создания.', verbose_name='Порядок (legacy)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_images', to='regions.region', verbose_name='Регион (legacy)'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Сегмент в URL. Уникален в пределах региона.', max_length=200, verbose_name='Slug')),
                ('title', models.CharField(max_length=300, verbose_name='Название альбома')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Название альбома')),
                ('title_kk', models.CharField(max_length=300, null=True, verbose_name='Название альбома')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Название альбома')),
                ('lead', models.TextField(blank=True, help_text='Опционально: 1–2 предложения для подсказки в backoffice.', verbose_name='Описание')),
                ('lead_ru', models.TextField(blank=True, help_text='Опционально: 1–2 предложения для подсказки в backoffice.', null=True, verbose_name='Описание')),
                ('lead_kk', models.TextField(blank=True, help_text='Опционально: 1–2 предложения для подсказки в backoffice.', null=True, verbose_name='Описание')),
                ('lead_en', models.TextField(blank=True, help_text='Опционально: 1–2 предложения для подсказки в backoffice.', null=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, help_text='Опциональная обложка для списка альбомов в backoffice. На сайте не выводится (там общая лента фото).', null=True, upload_to='gallery/albums/covers/', verbose_name='Обложка альбома')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(help_text='Тема альбома — chip-фильтр на странице галереи.', on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='gallery.gallerycategory', verbose_name='Тема (категория)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_albums', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='album',
            field=models.ForeignKey(blank=True, help_text='Альбом, в который входит фотография. На паблике сортируется по `-created_at` (свежие сверху).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.album', verbose_name='Альбом'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('region', 'slug'), name='gallery_album_region_slug_unique'),
        ),
    ]
