# Generated by Django 5.2.14 on 2026-05-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_cleanup_inactive_region_data'),
        ('team', '0003_teammember_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='grade_groups',
            field=models.ManyToManyField(blank=True, help_text='Группы классов, в которых преподаёт. Пусто — администрация (директор, координатор и т.п.) — показывается во вкладке «Все».', related_name='team_members', to='admission.gradegroup', verbose_name='Преподаёт в классах'),
        ),
    ]
