# Generated by Django 5.2.14 on 2026-05-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_seed_team_grade_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamResumeItem',
        ),
    ]
