# Generated by Django 5.2.14 on 2026-05-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_delete_teamresumeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Если включено — попадает в блок «Команда профессионалов» на странице «Программа» текущего региона. Порядок наследуется из поля «Порядок».', verbose_name='Избранный (на лендинге программы)'),
        ),
    ]
