# Generated by Django 5.2.14 on 2026-05-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_seed_featured_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='grade_groups',
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_admin',
            field=models.BooleanField(db_index=True, default=False, help_text='Директор, координатор, куратор — отдельный chip на странице /team/. Не зависит от teaches_*: учитель-завуч может быть и преподавателем, и администрацией одновременно.', verbose_name='Администрация'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='teaches_middle',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Средние классы (5–8)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='teaches_primary',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Младшие классы (1–4)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='teaches_senior',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Старшие классы (9–11)'),
        ),
    ]
