# Generated by Django 5.2.14 on 2026-05-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_seed_team_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='og_image',
        ),
    ]
