# Generated by Django 5.2.14 on 2026-05-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0005_seed_inactive_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, db_index=True, help_text='Семантический тег места вызова модалки: hero, program-hero, admission-cambridge-grade-1, activity-12-group-3 и т.п.', max_length=120, verbose_name='Источник (origin)')),
                ('title', models.CharField(blank=True, help_text='Контекстный заголовок, который видел пользователь (напр. «Запишитесь на бесплатную консультацию»).', max_length=200, verbose_name='Заголовок модалки')),
                ('category', models.CharField(choices=[('admission', 'Поступление'), ('program', 'Программа'), ('activity', 'Внеклассные'), ('general', 'Общая')], db_index=True, default='general', help_text='Авто-вывод из origin при создании. После можно переопределить вручную.', max_length=20, verbose_name='Категория')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, help_text='Если модалка открывалась с data-feedback-city, тут выбор пользователя (Астана/Актау/…).', max_length=80, verbose_name='Город (из формы)')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Закрыта успешно'), ('rejected', 'Отказ/спам')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('manager_note', models.TextField(blank=True, help_text='Что по звонку, договорённости, отказ и причина.', verbose_name='Заметка менеджера')),
                ('consented_at', models.DateTimeField(auto_now_add=True, help_text='Момент отправки формы = момент согласия. Снимает споры «я не давал согласия».', verbose_name='Согласие получено')),
                ('policy_version', models.CharField(default='v1', help_text='Фиксируется при создании. Меняется через настройки при выпуске новой редакции политики.', max_length=20, verbose_name='Версия политики')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('region', models.ForeignKey(help_text='Регион страницы, с которой пришла заявка. Не путать с городом, выбранным в форме.', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
