# Generated by Django 5.2.14 on 2026-05-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0003_alter_region_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, help_text='Фоновое изображение под hero-блоком (например, здание школы).', null=True, upload_to='home/hero/', verbose_name='Фон hero')),
                ('hero_badge_text', models.CharField(help_text='Маленький ярлычок над h1.', max_length=120, verbose_name='Бадж над заголовком')),
                ('hero_badge_text_ru', models.CharField(help_text='Маленький ярлычок над h1.', max_length=120, null=True, verbose_name='Бадж над заголовком')),
                ('hero_badge_text_kk', models.CharField(help_text='Маленький ярлычок над h1.', max_length=120, null=True, verbose_name='Бадж над заголовком')),
                ('hero_badge_text_en', models.CharField(help_text='Маленький ярлычок над h1.', max_length=120, null=True, verbose_name='Бадж над заголовком')),
                ('hero_title', models.TextField(help_text='Каждая строка → отдельный <span class="hero-fit"> (на мобиле fitty подгоняет шрифт построчно).', verbose_name='Заголовок hero (h1)')),
                ('hero_title_ru', models.TextField(help_text='Каждая строка → отдельный <span class="hero-fit"> (на мобиле fitty подгоняет шрифт построчно).', null=True, verbose_name='Заголовок hero (h1)')),
                ('hero_title_kk', models.TextField(help_text='Каждая строка → отдельный <span class="hero-fit"> (на мобиле fitty подгоняет шрифт построчно).', null=True, verbose_name='Заголовок hero (h1)')),
                ('hero_title_en', models.TextField(help_text='Каждая строка → отдельный <span class="hero-fit"> (на мобиле fitty подгоняет шрифт построчно).', null=True, verbose_name='Заголовок hero (h1)')),
                ('hero_subtitle', models.TextField(help_text='Перенос строки = <br class="hidden md:block"> (виден только на десктопе).', verbose_name='Подзаголовок hero (h2)')),
                ('hero_subtitle_ru', models.TextField(help_text='Перенос строки = <br class="hidden md:block"> (виден только на десктопе).', null=True, verbose_name='Подзаголовок hero (h2)')),
                ('hero_subtitle_kk', models.TextField(help_text='Перенос строки = <br class="hidden md:block"> (виден только на десктопе).', null=True, verbose_name='Подзаголовок hero (h2)')),
                ('hero_subtitle_en', models.TextField(help_text='Перенос строки = <br class="hidden md:block"> (виден только на десктопе).', null=True, verbose_name='Подзаголовок hero (h2)')),
                ('hero_cta_primary_text', models.CharField(max_length=80, verbose_name='Текст основной CTA')),
                ('hero_cta_primary_text_ru', models.CharField(max_length=80, null=True, verbose_name='Текст основной CTA')),
                ('hero_cta_primary_text_kk', models.CharField(max_length=80, null=True, verbose_name='Текст основной CTA')),
                ('hero_cta_primary_text_en', models.CharField(max_length=80, null=True, verbose_name='Текст основной CTA')),
                ('hero_cta_secondary_text', models.CharField(max_length=80, verbose_name='Текст вторичной CTA')),
                ('hero_cta_secondary_text_ru', models.CharField(max_length=80, null=True, verbose_name='Текст вторичной CTA')),
                ('hero_cta_secondary_text_kk', models.CharField(max_length=80, null=True, verbose_name='Текст вторичной CTA')),
                ('hero_cta_secondary_text_en', models.CharField(max_length=80, null=True, verbose_name='Текст вторичной CTA')),
                ('about_label', models.CharField(help_text='Маленькая надпись над заголовком (например, «Кому подходит»).', max_length=80, verbose_name='Лейбл секции «О нас»')),
                ('about_label_ru', models.CharField(help_text='Маленькая надпись над заголовком (например, «Кому подходит»).', max_length=80, null=True, verbose_name='Лейбл секции «О нас»')),
                ('about_label_kk', models.CharField(help_text='Маленькая надпись над заголовком (например, «Кому подходит»).', max_length=80, null=True, verbose_name='Лейбл секции «О нас»')),
                ('about_label_en', models.CharField(help_text='Маленькая надпись над заголовком (например, «Кому подходит»).', max_length=80, null=True, verbose_name='Лейбл секции «О нас»')),
                ('about_title', models.TextField(help_text='Перенос строки = <br>.', verbose_name='Заголовок секции «О нас»')),
                ('about_title_ru', models.TextField(help_text='Перенос строки = <br>.', null=True, verbose_name='Заголовок секции «О нас»')),
                ('about_title_kk', models.TextField(help_text='Перенос строки = <br>.', null=True, verbose_name='Заголовок секции «О нас»')),
                ('about_title_en', models.TextField(help_text='Перенос строки = <br>.', null=True, verbose_name='Заголовок секции «О нас»')),
                ('about_body', models.TextField(help_text='Пустая строка = новый параграф.', verbose_name='Текст секции «О нас»')),
                ('about_body_ru', models.TextField(help_text='Пустая строка = новый параграф.', null=True, verbose_name='Текст секции «О нас»')),
                ('about_body_kk', models.TextField(help_text='Пустая строка = новый параграф.', null=True, verbose_name='Текст секции «О нас»')),
                ('about_body_en', models.TextField(help_text='Пустая строка = новый параграф.', null=True, verbose_name='Текст секции «О нас»')),
                ('video_file', models.FileField(blank=True, help_text='Mp4 для видео-блока. Если пусто — блок не отрисовывается.', null=True, upload_to='home/video/', verbose_name='Видео')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='home_page', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главные страницы',
            },
        ),
        migrations.CreateModel(
            name='HomeGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/gallery/', verbose_name='Картинка')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt-текст')),
                ('alt_text_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt-текст')),
                ('alt_text_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt-текст')),
                ('alt_text_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt-текст')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='pages.homepage', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Картинка галереи',
                'verbose_name_plural': 'Картинки галереи',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
