# Generated by Django 5.2.14 on 2026-05-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_seed_home_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Фоновое изображение под hero-блоком (например, здание школы). WebP и сжатая JPEG/PNG версии генерируются автоматически.', null=True, upload_to='home/hero/', verbose_name='Фон hero'),
        ),
    ]
