# Generated by Django 5.2.14 on 2026-05-11 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_homepage_hero_image'),
        ('regions', '0005_seed_inactive_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('intro_title_ru', models.CharField(max_length=120, null=True, verbose_name='Заголовок')),
                ('intro_title_kk', models.CharField(max_length=120, null=True, verbose_name='Заголовок')),
                ('intro_title_en', models.CharField(max_length=120, null=True, verbose_name='Заголовок')),
                ('intro_text', models.TextField(help_text='Параграф под заголовком.', verbose_name='Описание')),
                ('intro_text_ru', models.TextField(help_text='Параграф под заголовком.', null=True, verbose_name='Описание')),
                ('intro_text_kk', models.TextField(help_text='Параграф под заголовком.', null=True, verbose_name='Описание')),
                ('intro_text_en', models.TextField(help_text='Параграф под заголовком.', null=True, verbose_name='Описание')),
                ('office_name', models.CharField(max_length=120, verbose_name='Название офиса')),
                ('office_name_ru', models.CharField(max_length=120, null=True, verbose_name='Название офиса')),
                ('office_name_kk', models.CharField(max_length=120, null=True, verbose_name='Название офиса')),
                ('office_name_en', models.CharField(max_length=120, null=True, verbose_name='Название офиса')),
                ('office_address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('office_address_ru', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('office_address_kk', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('office_address_en', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('office_hours', models.CharField(help_text='Напр. «Пн–Пт, 09:00–18:00».', max_length=120, verbose_name='Часы работы офиса')),
                ('office_hours_ru', models.CharField(help_text='Напр. «Пн–Пт, 09:00–18:00».', max_length=120, null=True, verbose_name='Часы работы офиса')),
                ('office_hours_kk', models.CharField(help_text='Напр. «Пн–Пт, 09:00–18:00».', max_length=120, null=True, verbose_name='Часы работы офиса')),
                ('office_hours_en', models.CharField(help_text='Напр. «Пн–Пт, 09:00–18:00».', max_length=120, null=True, verbose_name='Часы работы офиса')),
                ('map_embed', models.TextField(blank=True, help_text='HTML iframe от Yandex/Google/2GIS. Если пусто — отрисуется серая заглушка.', verbose_name='Embed-код карты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contacts_page', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Страница «Контакты»',
                'verbose_name_plural': 'Страницы «Контакты»',
            },
        ),
        migrations.CreateModel(
            name='ContactsDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название отдела')),
                ('title_ru', models.CharField(max_length=120, null=True, verbose_name='Название отдела')),
                ('title_kk', models.CharField(max_length=120, null=True, verbose_name='Название отдела')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Название отдела')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_kk', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('phone', models.CharField(blank=True, help_text='Если пусто — строка не отрисуется.', max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('hours', models.CharField(blank=True, help_text='Напр. «Пн–Пт, 09:00–18:00». Если пусто — строка скрыта.', max_length=120, verbose_name='Часы работы')),
                ('hours_ru', models.CharField(blank=True, help_text='Напр. «Пн–Пт, 09:00–18:00». Если пусто — строка скрыта.', max_length=120, null=True, verbose_name='Часы работы')),
                ('hours_kk', models.CharField(blank=True, help_text='Напр. «Пн–Пт, 09:00–18:00». Если пусто — строка скрыта.', max_length=120, null=True, verbose_name='Часы работы')),
                ('hours_en', models.CharField(blank=True, help_text='Напр. «Пн–Пт, 09:00–18:00». Если пусто — строка скрыта.', max_length=120, null=True, verbose_name='Часы работы')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('contacts_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='pages.contactspage', verbose_name='Страница «Контакты»')),
            ],
            options={
                'verbose_name': 'Отдел контактов',
                'verbose_name_plural': 'Отделы контактов',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
