# Generated by Django 5.2.14 on 2026-05-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_seed_contacts_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactspage',
            name='map_embed',
        ),
        migrations.AddField(
            model_name='contactspage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Десятичные градусы, напр. 51.093900. Если широта или долгота пуста — карта не отрисуется, покажется серая заглушка.', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Десятичные градусы, напр. 71.401100.', max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='map_zoom',
            field=models.PositiveSmallIntegerField(default=16, help_text='Целое 1–19 (Leaflet/CartoDB). 16 — улица + здание.', verbose_name='Zoom карты'),
        ),
    ]
