# Generated by Django 5.2.14 on 2026-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_seed_legal_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegalleryimage',
            name='orientation',
            field=models.CharField(choices=[('wide', 'Широкая'), ('tall', 'Высокая'), ('square', 'Квадратная')], default='square', help_text='Определяется автоматически при загрузке (wide/tall/square).', max_length=8, verbose_name='Ориентация'),
        ),
    ]
