# Generated by Django 5.2.14 on 2026-05-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_backfill_homegallery_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_primary_modal_title',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на текст кнопки.', max_length=80, verbose_name='Заголовок модалки primary CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_primary_modal_title_en',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на текст кнопки.', max_length=80, null=True, verbose_name='Заголовок модалки primary CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_primary_modal_title_kk',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на текст кнопки.', max_length=80, null=True, verbose_name='Заголовок модалки primary CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_primary_modal_title_ru',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на текст кнопки.', max_length=80, null=True, verbose_name='Заголовок модалки primary CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_secondary_modal_title',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на текст кнопки.', max_length=80, verbose_name='Заголовок модалки secondary CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_secondary_modal_title_en',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на текст кнопки.', max_length=80, null=True, verbose_name='Заголовок модалки secondary CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_secondary_modal_title_kk',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на текст кнопки.', max_length=80, null=True, verbose_name='Заголовок модалки secondary CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_secondary_modal_title_ru',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на текст кнопки.', max_length=80, null=True, verbose_name='Заголовок модалки secondary CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_description',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_description → hero_subtitle.', max_length=300, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_description_en',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_description → hero_subtitle.', max_length=300, null=True, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_description_kk',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_description → hero_subtitle.', max_length=300, null=True, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_description_ru',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_description → hero_subtitle.', max_length=300, null=True, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='1200×630 для соцсетей. Если пусто — fallback на hero_image (но он прозрачный — в соцсетях будет некрасиво).', null=True, upload_to='home/og/', verbose_name='OG/share картинка'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_title → hero_title.', max_length=80, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_title_en',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_title → hero_title.', max_length=80, null=True, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_title_kk',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_title → hero_title.', max_length=80, null=True, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_title_ru',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_title → hero_title.', max_length=80, null=True, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_description',
            field=models.CharField(blank=True, help_text='150–160 символов. Если пусто — fallback на hero_subtitle.', max_length=200, verbose_name='SEO description (meta)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_description_en',
            field=models.CharField(blank=True, help_text='150–160 символов. Если пусто — fallback на hero_subtitle.', max_length=200, null=True, verbose_name='SEO description (meta)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_description_kk',
            field=models.CharField(blank=True, help_text='150–160 символов. Если пусто — fallback на hero_subtitle.', max_length=200, null=True, verbose_name='SEO description (meta)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_description_ru',
            field=models.CharField(blank=True, help_text='150–160 символов. Если пусто — fallback на hero_subtitle.', max_length=200, null=True, verbose_name='SEO description (meta)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='50–60 символов. Если пусто — fallback на hero_title.', max_length=80, verbose_name='SEO title (<title>)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='50–60 символов. Если пусто — fallback на hero_title.', max_length=80, null=True, verbose_name='SEO title (<title>)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title_kk',
            field=models.CharField(blank=True, help_text='50–60 символов. Если пусто — fallback на hero_title.', max_length=80, null=True, verbose_name='SEO title (<title>)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title_ru',
            field=models.CharField(blank=True, help_text='50–60 символов. Если пусто — fallback на hero_title.', max_length=80, null=True, verbose_name='SEO title (<title>)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video_file',
            field=models.FileField(blank=True, help_text='Mp4 для видео-блока. Если пусто — блок не отрисовывается.', null=True, upload_to='home/video/', verbose_name='Шоурил'),
        ),
    ]
