# Generated by Django 5.2.14 on 2026-05-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_homepage_seo_cta_modal'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_poster',
            field=models.ImageField(blank=True, help_text='Автоматически генерируется из 1-й секунды видео при сохранении. Показывается до старта воспроизведения (важен для UX на медленном соединении и для SEO).', null=True, upload_to='home/video_posters/', verbose_name='Poster (1-й кадр)'),
        ),
    ]
