# Generated by Django 5.2.14 on 2026-05-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_backfill_video_posters'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='og_description',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_description → intro_text.', max_length=300, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='og_description_en',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_description → intro_text.', max_length=300, null=True, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='og_description_kk',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_description → intro_text.', max_length=300, null=True, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='og_description_ru',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_description → intro_text.', max_length=300, null=True, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='1200×630 для соцсетей. Если пусто — на сайте OG-картинки не будет (контакты — обычно не share-target).', null=True, upload_to='contacts/og/', verbose_name='OG/share картинка'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_title → intro_title.', max_length=80, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='og_title_en',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_title → intro_title.', max_length=80, null=True, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='og_title_kk',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_title → intro_title.', max_length=80, null=True, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='og_title_ru',
            field=models.CharField(blank=True, help_text='Если пусто — fallback на seo_title → intro_title.', max_length=80, null=True, verbose_name='OG title'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='seo_description',
            field=models.CharField(blank=True, help_text='150–160 символов. Если пусто — fallback на intro_text.', max_length=200, verbose_name='SEO description (meta)'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='seo_description_en',
            field=models.CharField(blank=True, help_text='150–160 символов. Если пусто — fallback на intro_text.', max_length=200, null=True, verbose_name='SEO description (meta)'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='seo_description_kk',
            field=models.CharField(blank=True, help_text='150–160 символов. Если пусто — fallback на intro_text.', max_length=200, null=True, verbose_name='SEO description (meta)'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='seo_description_ru',
            field=models.CharField(blank=True, help_text='150–160 символов. Если пусто — fallback на intro_text.', max_length=200, null=True, verbose_name='SEO description (meta)'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='50–60 символов. Если пусто — fallback на intro_title.', max_length=80, verbose_name='SEO title (<title>)'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='50–60 символов. Если пусто — fallback на intro_title.', max_length=80, null=True, verbose_name='SEO title (<title>)'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='seo_title_kk',
            field=models.CharField(blank=True, help_text='50–60 символов. Если пусто — fallback на intro_title.', max_length=80, null=True, verbose_name='SEO title (<title>)'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='seo_title_ru',
            field=models.CharField(blank=True, help_text='50–60 символов. Если пусто — fallback на intro_title.', max_length=80, null=True, verbose_name='SEO title (<title>)'),
        ),
    ]
