# Generated by Django 5.2.14 on 2026-05-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_flatpage_og_description_flatpage_og_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='telegram_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='Telegram URL'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='TikTok URL'),
        ),
    ]
