# Generated by Django 5.2.14 on 2026-05-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_flatpagegallery_flatpagegalleryimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactspage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='flatpage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='og_image',
        ),
    ]
