# Generated by Django 5.2.14 on 2026-05-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0005_seed_inactive_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Машинное имя категории (для ?category=...). Только латиница.', max_length=64, verbose_name='Slug')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=80, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=80, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=80, null=True, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_categories', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=80, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=80, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=80, null=True, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_tags', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Тег блога',
                'verbose_name_plural': 'Теги блога',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Сегмент в URL: my-post-title. Уникален в пределах региона.', max_length=200, verbose_name='Slug')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок (h1)')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Заголовок (h1)')),
                ('title_kk', models.CharField(max_length=300, null=True, verbose_name='Заголовок (h1)')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Заголовок (h1)')),
                ('lead', models.TextField(blank=True, help_text='Опционально: 1–2 предложения для превью и meta description.', verbose_name='Лид')),
                ('lead_ru', models.TextField(blank=True, help_text='Опционально: 1–2 предложения для превью и meta description.', null=True, verbose_name='Лид')),
                ('lead_kk', models.TextField(blank=True, help_text='Опционально: 1–2 предложения для превью и meta description.', null=True, verbose_name='Лид')),
                ('lead_en', models.TextField(blank=True, help_text='Опционально: 1–2 предложения для превью и meta description.', null=True, verbose_name='Лид')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Обложка')),
                ('cover_caption', models.CharField(blank=True, help_text='Опциональный figcaption под обложкой в теле статьи.', max_length=300, verbose_name='Подпись под обложкой')),
                ('cover_caption_ru', models.CharField(blank=True, help_text='Опциональный figcaption под обложкой в теле статьи.', max_length=300, null=True, verbose_name='Подпись под обложкой')),
                ('cover_caption_kk', models.CharField(blank=True, help_text='Опциональный figcaption под обложкой в теле статьи.', max_length=300, null=True, verbose_name='Подпись под обложкой')),
                ('cover_caption_en', models.CharField(blank=True, help_text='Опциональный figcaption под обложкой в теле статьи.', max_length=300, null=True, verbose_name='Подпись под обложкой')),
                ('cover_alt', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется title.', max_length=300, verbose_name='Alt-текст обложки')),
                ('cover_alt_ru', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется title.', max_length=300, null=True, verbose_name='Alt-текст обложки')),
                ('cover_alt_kk', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется title.', max_length=300, null=True, verbose_name='Alt-текст обложки')),
                ('cover_alt_en', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется title.', max_length=300, null=True, verbose_name='Alt-текст обложки')),
                ('content', models.TextField(help_text='HTML рендерится через |safe. Используй h2/h3/h4, p, ul/ol/li, blockquote+cite, a, img, figure+figcaption, small.', verbose_name='Содержимое (HTML)')),
                ('content_ru', models.TextField(help_text='HTML рендерится через |safe. Используй h2/h3/h4, p, ul/ol/li, blockquote+cite, a, img, figure+figcaption, small.', null=True, verbose_name='Содержимое (HTML)')),
                ('content_kk', models.TextField(help_text='HTML рендерится через |safe. Используй h2/h3/h4, p, ul/ol/li, blockquote+cite, a, img, figure+figcaption, small.', null=True, verbose_name='Содержимое (HTML)')),
                ('content_en', models.TextField(help_text='HTML рендерится через |safe. Используй h2/h3/h4, p, ul/ol/li, blockquote+cite, a, img, figure+figcaption, small.', null=True, verbose_name='Содержимое (HTML)')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(db_index=True, help_text='Сортировка ленты и показ даты на карточке.', verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.blogcategory', verbose_name='Категория')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to='regions.region', verbose_name='Регион')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-published_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='blogcategory',
            constraint=models.UniqueConstraint(fields=('region', 'slug'), name='blog_category_region_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='blogtag',
            constraint=models.UniqueConstraint(fields=('region', 'slug'), name='blog_tag_region_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.UniqueConstraint(fields=('region', 'slug'), name='blog_post_region_slug_unique'),
        ),
    ]
