# Generated by Django 5.2.14 on 2026-05-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Ссылка в шорткоде: [[gallery slug=ЭТО]]. Уникален в пределах статьи.', max_length=64, verbose_name='Slug')),
                ('title', models.CharField(blank=True, help_text='Внутренняя метка для админки; не выводится на сайте.', max_length=200, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='blog.blogpost', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Фотогалерея',
                'verbose_name_plural': 'Фотогалереи',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BlogGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/galleries/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, help_text='Опциональный figcaption под картинкой.', max_length=300, verbose_name='Подпись')),
                ('caption_ru', models.CharField(blank=True, help_text='Опциональный figcaption под картинкой.', max_length=300, null=True, verbose_name='Подпись')),
                ('caption_kk', models.CharField(blank=True, help_text='Опциональный figcaption под картинкой.', max_length=300, null=True, verbose_name='Подпись')),
                ('caption_en', models.CharField(blank=True, help_text='Опциональный figcaption под картинкой.', max_length=300, null=True, verbose_name='Подпись')),
                ('alt', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется подпись или название галереи.', max_length=300, verbose_name='Alt-текст')),
                ('alt_ru', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется подпись или название галереи.', max_length=300, null=True, verbose_name='Alt-текст')),
                ('alt_kk', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется подпись или название галереи.', max_length=300, null=True, verbose_name='Alt-текст')),
                ('alt_en', models.CharField(blank=True, help_text='Для SEO/доступности. Если пусто — подставляется подпись или название галереи.', max_length=300, null=True, verbose_name='Alt-текст')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.bloggallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Фото в галерее',
                'verbose_name_plural': 'Фото в галерее',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='bloggallery',
            constraint=models.UniqueConstraint(fields=('post', 'slug'), name='blog_gallery_post_slug_unique'),
        ),
    ]
