# Generated by Django 5.2.14 on 2026-05-18 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_cover_image_optional'),
        ('team', '0010_seed_team_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Автор статьи из раздела «Команда». Доступны члены команды того же региона. Если не указан — на сайте автор не выводится.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='team.teammember', verbose_name='Автор'),
        ),
    ]
