# Generated by Django 5.2.14 on 2026-05-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='og_image',
        ),
    ]
