# Generated by Django 5.2.14 on 2026-05-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Сегмент в URL: astana, aktau. Только латиница.', max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('is_default', models.BooleanField(default=False, help_text='Пометить ровно один регион. Для корневого URL и для пользователей без выбора.', verbose_name='Регион по умолчанию')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('address_kk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['slug'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='regions_only_one_default')],
            },
        ),
    ]
