# Generated by Django 5.2.14 on 2026-05-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_seed_regions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['-is_default', 'slug'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
