# Generated by Django 5.2.14 on 2026-05-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['-is_active', '-is_default', 'slug'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.RemoveField(
            model_name='region',
            name='address',
        ),
        migrations.RemoveField(
            model_name='region',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='region',
            name='address_kk',
        ),
        migrations.RemoveField(
            model_name='region',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='region',
            name='phone',
        ),
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если выключен — регион не показывается в переключателе и URL `/<lang>/<slug>/` возвращает 404. Используется для городов, которые добавлены «на будущее».', verbose_name='Активен'),
        ),
    ]
