# Generated by Django 5.2.14 on 2026-05-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_seed_program_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programactivityitem',
            name='category_color',
            field=models.CharField(choices=[('indigo', 'Индиго (Технологии)'), ('red', 'Красный (Наука)'), ('green', 'Зелёный (Риторика)'), ('orange', 'Оранжевый (Спорт)')], default='indigo', max_length=20, verbose_name='Цвет категории'),
        ),
    ]
