# Generated by Django 5.2.14 on 2026-05-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_programactivityitem_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programpage',
            name='hero_title',
            field=models.TextField(help_text='HTML-разметка (рендерится через |safe). Используй <span class="hero-fit">…</span> для построчной подгонки шрифта на мобиле; внутри можно <span class="hero-break">…</span> (десктопный перенос) и <span class="text-gold">…</span> для акцента. Пример: <span class="hero-fit">Школа для детей</span><span class="hero-fit">которые <span class="hero-break">поступят</span></span><span class="hero-fit">в <span class="text-gold">TOP-100</span> вузов</span>', verbose_name='Заголовок hero (h1)'),
        ),
        migrations.AlterField(
            model_name='programpage',
            name='hero_title_en',
            field=models.TextField(help_text='HTML-разметка (рендерится через |safe). Используй <span class="hero-fit">…</span> для построчной подгонки шрифта на мобиле; внутри можно <span class="hero-break">…</span> (десктопный перенос) и <span class="text-gold">…</span> для акцента. Пример: <span class="hero-fit">Школа для детей</span><span class="hero-fit">которые <span class="hero-break">поступят</span></span><span class="hero-fit">в <span class="text-gold">TOP-100</span> вузов</span>', null=True, verbose_name='Заголовок hero (h1)'),
        ),
        migrations.AlterField(
            model_name='programpage',
            name='hero_title_kk',
            field=models.TextField(help_text='HTML-разметка (рендерится через |safe). Используй <span class="hero-fit">…</span> для построчной подгонки шрифта на мобиле; внутри можно <span class="hero-break">…</span> (десктопный перенос) и <span class="text-gold">…</span> для акцента. Пример: <span class="hero-fit">Школа для детей</span><span class="hero-fit">которые <span class="hero-break">поступят</span></span><span class="hero-fit">в <span class="text-gold">TOP-100</span> вузов</span>', null=True, verbose_name='Заголовок hero (h1)'),
        ),
        migrations.AlterField(
            model_name='programpage',
            name='hero_title_ru',
            field=models.TextField(help_text='HTML-разметка (рендерится через |safe). Используй <span class="hero-fit">…</span> для построчной подгонки шрифта на мобиле; внутри можно <span class="hero-break">…</span> (десктопный перенос) и <span class="text-gold">…</span> для акцента. Пример: <span class="hero-fit">Школа для детей</span><span class="hero-fit">которые <span class="hero-break">поступят</span></span><span class="hero-fit">в <span class="text-gold">TOP-100</span> вузов</span>', null=True, verbose_name='Заголовок hero (h1)'),
        ),
    ]
