# Generated by Django 5.2.14 on 2026-05-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_seed_activity_group_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramActivityItem',
        ),
    ]
