# Generated by Django 5.2.14 on 2026-05-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_programpage_og_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramTeamMember',
        ),
    ]
