# Generated by Django 5.2.14 on 2026-05-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_aktau_single_program_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstat',
            name='label',
            field=models.CharField(help_text='Для переноса строки нажми Enter. HTML экранируется.', max_length=120, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='programstat',
            name='label_en',
            field=models.CharField(help_text='Для переноса строки нажми Enter. HTML экранируется.', max_length=120, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='programstat',
            name='label_kk',
            field=models.CharField(help_text='Для переноса строки нажми Enter. HTML экранируется.', max_length=120, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='programstat',
            name='label_ru',
            field=models.CharField(help_text='Для переноса строки нажми Enter. HTML экранируется.', max_length=120, null=True, verbose_name='Подпись'),
        ),
    ]
