# Generated by Django 5.2.14 on 2026-05-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_alter_programstat_label_alter_programstat_label_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programpage',
            name='og_image',
        ),
    ]
