# Generated by Django 5.2.14 on 2026-05-11 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Технический идентификатор секции: main, school-life. Только латиница.', max_length=32, unique=True)),
                ('label', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('label_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('label_kk', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('label_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(default=0, help_text='Колонки сортируются по возрастанию. Шаг 10 — оставляет место для вставки.', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Секция мегаменю',
                'verbose_name_plural': 'Секции мегаменю',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Идентификатор для подсветки активной ссылки (active_page). Только латиница.', max_length=64, unique=True)),
                ('label', models.CharField(max_length=120, verbose_name='Подпись')),
                ('label_ru', models.CharField(max_length=120, null=True, verbose_name='Подпись')),
                ('label_kk', models.CharField(max_length=120, null=True, verbose_name='Подпись')),
                ('label_en', models.CharField(max_length=120, null=True, verbose_name='Подпись')),
                ('url_name', models.CharField(blank=True, help_text='Django URL name, напр. pages:about. Пусто — пункт-заглушка с href="#".', max_length=120, verbose_name='URL name')),
                ('is_top_nav', models.BooleanField(default=False, help_text='Дополнительно выводить этот пункт в верхней навигации (десктоп). Дубликат в мегаменю остаётся.', verbose_name='В шапке')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, help_text='Снять флаг, чтобы временно убрать пункт из навигации, не удаляя.', verbose_name='Опубликован')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigation.navsection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Пункт навигации',
                'verbose_name_plural': 'Пункты навигации',
                'ordering': ['section__order', 'order', 'pk'],
            },
        ),
    ]
