# Generated by Django 5.2.14 on 2026-05-15 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_events_first_in_school_life'),
        ('pages', '0011_flatpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='flat_page',
            field=models.ForeignKey(blank=True, help_text='Если задано — ссылка ведёт на FlatPage (приоритет над url_name). Регион подставляется автоматически.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_items', to='pages.flatpage', verbose_name='Статичная страница'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='url_name',
            field=models.CharField(blank=True, help_text='Django URL name, напр. pages:home. Пусто — пункт-заглушка с href="#". Если задан flat_page, поле игнорируется.', max_length=120, verbose_name='URL name'),
        ),
    ]
